
# =============================================================================
# BLACK
# =============================================================================

[tool.black]
line-length = 79
target-version = ["py37", "py38"]


# =============================================================================
# FLAKE8
# =============================================================================

[tool.flakehell.plugins]
pycodestyle = ["-E402"]
pyflakes = ["+*"]
flake8-bandit = ["+*"]
flake8-black = ["+*"]
flake8-bugbear = ["+*"]
flake8-import-order-flake8-linter = ["+*"]

# match by prefix
[tool.flakehell.exceptions."test_prj/"]
flake8-bandit = ["-S101"]


# =============================================================================
# TOX
# =============================================================================

[tool.tox]
legacy_tox_ini = """
[tox]
envlist = docstyle, style, py37, py38

[testenv]
deps =
    ipdb
    pyquery
    pytest
    pytest-mock
    pytest-django
changedir = test_prj
commands =
    pytest --ds "test_prj.settings" -v {posargs}

[testenv:docstyle]
deps = pydocstyle
commands =
    pydocstyle django_matplotlib --convention=numpy

[testenv:style]
skip_install = True
usedevelop = False
deps =
    flake8
    flake8-import-order
    flake8-bugbear
    flake8-bandit
    flake8-black
    flakehell
commands =
    flakehell lint setup.py test_prj django_matplotlib {posargs}
"""