
[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ["py37", "py38"]


[tool.flake8]
per-file-ignores = "test_prj/*:S101"
ignore = "E402"


[tool.pytest]
DJANGO_SETTINGS_MODULE = "test_prj.settings"


[tool.tox]
legacy_tox_ini = """
[tox]
envlist = style, py37, py38

[testenv]
deps =
    ipdb
    pyquery
    pytest
    pytest-mock
    pytest-django
commands =
    pytest --rootdir test_prj -v {posargs}


[testenv:style]
skip_install = True
usedevelop = False
deps =
    flake8
    flake8-import-order
    flake8-bugbear
    flake8-bandit
    flake8-black
commands =
    flake8 setup.py test_prj django_matplotlib {posargs}
"""