#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (c) 2020, Juan B Cabral & QuatroPe
# License: BSD-3-Clause
#   Full Text: https://github.com/quatrope/djmpl/blob/master/LICENSE


# =============================================================================
# DOCS
# =============================================================================

"""This file is for distribute django-matplotlib

"""


# =============================================================================
# IMPORTS
# =============================================================================

import os
import pathlib

from ez_setup import use_setuptools

use_setuptools()

from setuptools import find_packages, setup


# =============================================================================
# CONSTANTS
# =============================================================================

PATH = pathlib.Path(os.path.abspath(os.path.dirname(__file__)))

REQUIREMENTS = ["django", "matplotlib", "attrs", "mpld3", "jinja2"]

with open(PATH / "README.md") as fp:
    LONG_DESCRIPTION = fp.read()

DESCRIPTION = (
    "Integration between django and the plots generated by matplotlib."
)

with open(PATH / "django_matplotlib" / "__init__.py") as fp:
    VERSION = (
        [line for line in fp.readlines() if line.startswith("__version__")][0]
        .split("=", 1)[-1]
        .strip()
        .replace('"', "")
    )


PACKAGES = find_packages()


# =============================================================================
# FUNCTIONS
# =============================================================================


def do_setup():
    setup(
        name="django_matplotlib",
        version=VERSION,
        description=DESCRIPTION,
        long_description=LONG_DESCRIPTION,
        long_description_content_type="text/markdown",
        author="J.B. Cabral",
        author_email="jbcabral@unc.edu.ar",
        url="https://django-matplotlib.readthedocs.io/",
        license="3 Clause BSD",
        keywords=["matplotlib", "plot", "django"],
        classifiers=(
            "Development Status :: 4 - Beta",
            "Intended Audience :: Education",
            "Intended Audience :: Science/Research",
            "License :: OSI Approved :: BSD License",
            "Operating System :: OS Independent",
            "Programming Language :: Python",
            "Programming Language :: Python :: 3.7",
            "Programming Language :: Python :: 3.8",
            "Programming Language :: Python :: 3.9",
            "Programming Language :: Python :: Implementation :: CPython",
            "Topic :: Scientific/Engineering",
        ),
        py_modules=["ez_setup"],
        packages=PACKAGES,
        install_requires=REQUIREMENTS,
        include_package_data=True,
    )


if __name__ == "__main__":
    do_setup()
