#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (c) 2020, Juan B Cabral & QuatroPe
# License: BSD-3-Clause
#   Full Text: https://github.com/quatrope/djmpl/blob/master/LICENSE


# =============================================================================
# DOCS
# =============================================================================

"""Integration between django and the plots generated by matplotlib.

"""

__version__ = "0.2.0"


# =============================================================================
# IMPORTS
# =============================================================================

from .core import subplots  # noqa